// Package mise extracts the toolchain declaration from a project's mise.toml.
package mise

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/pelletier/go-toml/v2"
)

// ExtractTools returns a mise.toml containing only the [tools] table.
//
// A real project mise.toml routinely carries [env] directives such as
// `_.source = ".env.dev"` and `_.path = [...]`, plus [tasks]. Those reference
// files that are not — and should not be — in the Docker build context, and
// they are irrelevant to installing toolchains. Copying the file wholesale
// makes `mise install` fail at build time; copying only [tools] is both
// necessary and sufficient. The project's full mise.toml is still on the bind
// mount and activates normally at runtime.
//
// A missing mise.toml yields an empty [tools] table rather than an error, so
// the Dockerfile's COPY always has something to copy.
func ExtractTools(projectDir string) (content string, toolCount int, err error) {
	path := filepath.Join(projectDir, "mise.toml")
	b, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "[tools]\n", 0, nil
		}
		return "", 0, err
	}

	var doc struct {
		Tools map[string]any `toml:"tools"`
	}
	if err := toml.Unmarshal(b, &doc); err != nil {
		return "", 0, fmt.Errorf("parsing %s: %w", path, err)
	}
	if len(doc.Tools) == 0 {
		return "[tools]\n", 0, nil
	}

	out, err := toml.Marshal(map[string]any{"tools": doc.Tools})
	if err != nil {
		return "", 0, err
	}
	return "# Generated by ccic from the project's mise.toml — [tools] only.\n" + string(out),
		len(doc.Tools), nil
}

// ToolNames lists the tools declared, for display in status and .ccic.md.
func ToolNames(projectDir string) []string {
	b, err := os.ReadFile(filepath.Join(projectDir, "mise.toml"))
	if err != nil {
		return nil
	}
	var doc struct {
		Tools map[string]any `toml:"tools"`
	}
	if toml.Unmarshal(b, &doc) != nil {
		return nil
	}
	names := make([]string, 0, len(doc.Tools))
	for k, v := range doc.Tools {
		names = append(names, fmt.Sprintf("%s=%v", k, v))
	}
	return names
}
